INSERT INTO `esic-catalogo`.city (city, domain, url)
VALUES 
    ('São Paulo','www.capital.sp.gov.br','esic.prefeitura.sp.gov.br/Account/Login.aspx'),
    ('Curitiba','www.curitiba.pr.gov.br','autenticacao-ecidadao.curitiba.pr.gov.br'),
    ('Sorocaba','www.sorocaba.sp.gov.br','transparencia.sorocaba.sp.gov.br/esic/wp_login.aspx?3552205,1'),
    ('Acre','acre.gov.br','esic.ac.gov.br/sistema/site/index.html?ReturnUrl=%2fsistema%2f'),
    ('Alagoas','www.agenciaalagoas.al.gov.br','e-sic.al.gov.br/login/?next=/'),
    ('Amazonas','www.amazonas.am.gov.br','acessoainformacao.am.gov.br/index/'),
    ('Amapá','www.portal.ap.gov.br','esic.ap.gov.br/'),
    ('Bahia','www.ba.gov.br','www.ouvidoria.ba.gov.br/'),
    ('Ceará','www.ceara.gov.br','cearatransparente.ce.gov.br/portal-da-transparencia/acesso-a-informacao?locale=pt-BR'),
    ('Distrito Federal','www.df.gov.br','www.e-sic.df.gov.br/Sistema/'),
    ('Espírito Santo','www.es.gov.br','sistema.ouvidoria.es.gov.br/publico/Manifestacao/RegistrarManifestacaoBs.aspx'),
    ('Goiás','www.goias.gov.br','www.cge.go.gov.br/ouvidoria/Register_1.php'),
    ('Maranhão','www3.ma.gov.br','www.e-sic.ma.gov.br/sistema/site/index.html'),
    ('Minas Gerais','www.mg.gov.br','www.acessoainformacao.mg.gov.br/sistema/site/index.html?ReturnUrl=%2fsistema%2f'),
    ('Mato Grosso do Sul','www.ms.gov.br','www.esic.ms.gov.br/'),
    ('Mato Grosso','www.mt.gov.br','ouvidoria.controladoria.mt.gov.br/falecidadao/servlet/cadastrardemanda?5'),
    ('Pará','www.pa.gov.br','www.sistemas.pa.gov.br/esic/public/main/index.xhtml'),
    ('Paraíba','paraiba.pb.gov.br','sic.pb.gov.br/paginas-sicpb/solicite-uma-informacao'),
    ('Pernambuco','www.sad.pe.gov.br/web','web.transparencia.pe.gov.br/acesso-a-informacao/faca-um-pedido-de-acesso-a-informacao/'),
    ('Piauí','www.pi.gov.br','acessoainformacao.pi.gov.br/sigep/'),
    ('Paraná','www.parana.pr.gov.br','www.transparencia.pr.gov.br/pte/acesso-a-informacao'),
    ('Rio de Janeiro','www.rj.gov.br','www.esicrj.rj.gov.br/'),
    ('Rio Grande do Norte','www.rn.gov.br','www.sic.rn.gov.br/Solicitacao/Incluir'),
    ('Rondônia','www.rondonia.ro.gov.br','esic.cge.ro.gov.br/'),
    ('Rio Grande do Sul','estado.rs.gov.br','sso.acesso.gov.br/login?client_id=logincidadao.rs.gov.br'),
    ('Santa Catarina','www.sc.gov.br','www.ouvidoria.sc.gov.br/cidadao/'),
    ('Sergipe','www.se.gov.br','se-ouv.se.gov.br/esic/index.xhtml'),
    ('Tocantins','portal.to.gov.br','www.gestao.cge.to.gov.br/ouvidoria/menuAciona/'),
    ('Ariquemes - RO','portal.to.gov.br','transparencia.ariquemes.ro.gov.br/transparencia/index.php?link=aplicacoes/esic/frmpedido&nomeaplicacao=esic'),
    ('Cacoal - RO','www.cacoal.ro.gov.br','transparencia.cacoal.ro.gov.br/portaltransparencia/esic'),
    ('Jaru - RO','jaru.ro.gov.br','transparencia.jaru.ro.gov.br/transparencia/index.php?link=aplicacoes/esic/frmpedido&nomeaplicacao=esic'),
    ('Ji-Paraná - RO','www.ji-parana.ro.gov.br','www.ji-parana.ro.gov.br/'),
    ('Porto Velho - RO','www.portovelho.ro.gov.br','esic.portovelho.ro.gov.br/sistema/Pessoa/CadastrarPessoa.aspx'),
    ('Rolim de Moura - RO','www.rolimdemoura.ro.gov.br','transparencia.rolimdemoura.ro.gov.br/portaltransparencia/esic'),
    ('Vilhena - RO','www.vilhena.ro.gov.br','esic.vilhena.ro.gov.br/'),
    ('Cruzeiro do Sul - AC','www.cruzeirodosul.ac.gov.br','e-gov.betha.com.br/transparencia/01037-090/con_registropedidoinformacao.faces'),
    ('Rio Branco - AC','www.riobranco.ac.gov.br','esic.riobranco.ac.gov.br/sistema/Pessoa/CadastrarPessoa.aspx'),
    ('Coari - AM','coari.am.gov.br','transparencia.coari.am.gov.br/sic-informacao/sic-login'),
    ('Humaitá - AM','www.humaita.am.gov.br/#','e-gov.betha.com.br/transparencia/01037-049/con_registropedidoinformacao.faces'),
    ('Itacoatiara - AM','www.itacoatiara.am.gov.br','www.transparencia-itacoatiara.org/'),
    ('Manaus - AM','www.manaus.am.gov.br','transparencia.manaus.am.gov.br/transparencia/v2/#/sicregistro'),
    ('Manicoré - AM','manicore.am.gov.br','perseusdata.com/PMmanicore/?page_id=139'),
    ('Maués - AM','www.maues.am.gov.br','transparenciamunicipalaam.org.br/esic/maues/solicitar-informacao'),
    ('Tefé - AM','tefe.am.gov.br','e-gov.betha.com.br/transparencia/01037-057/con_consultapedidoinformacao.faces'),
    ('Boa Vista - RR','www.boavista.rr.gov.br','transparencia.boavista.rr.gov.br/acesso-informacao'),
    ('Abaetetuba - PA','www.abaetetuba.pa.gov.br','www.abaetetuba.pa.gov.br/sic.php'),
    ('Acará - PA','acara.pa.gov.br','acara.pa.gov.br/solicitacoes/index.php?a=add&category=1'),
    ('Alenquer - PA','alenquer.pa.gov.br','www.gdic.com.br/modulo/esic/login/4361489'),
    ('Altamira - PA','altamira.pa.gov.br/site','altamira.pa.gov.br/site/e-sic/'),
    ('Barcarena - PA','www.barcarena.pa.gov.br/portal','www.gdic.com.br/modulo/esic/login/4382489'),
    ('Belém - PA','www.belem.pa.gov.br','www.belem.pa.gov.br/ouvidoria/'),
    ('Benevides - PA','benevides.pa.gov.br/defaul','www.benevides.pa.gov.br/transparencia/esic/41/'),
    ('Bragança - PA','www.braganca.pa.gov.br/app/pmb','www.braganca.pa.gov.br/acesso_informacao/index/'),
    ('Breu Branco - PA','www.breubranco.pa.gov.br/site','www.breubranco.pa.gov.br/transparencia/esic.html'),
    ('Breves - PA','breves.pa.gov.br','breves.pa.gov.br/solicitar-informacao/'),
    ('Cametá - PA','prefeituradecameta.pa.gov.br','prefeituradecameta.pa.gov.br/e-sic/index.php?a=add'),
    ('Capanema - PA','www.capanema.pa.gov.br','www.capanema.pa.gov.br/sic.php'),
    ('Capitão Poço - PA','www.capitaopoco.pa.gov.br','www.capitaopoco.pa.gov.br/cp/e-sic'),
    ('Castanhal - PA','www.castanhal.pa.gov.br','www.castanhal.pa.gov.br/acesso-a-informacao/#eSIC'),
    ('Dom Eliseu - PA','domeliseu.pa.gov.br','domeliseu.pa.gov.br/solicitacoes/index.php?a=add&category=1'),
    ('Igarapé-Miri - PA','igarapemiri.pa.gov.br','igarapemiri.pa.gov.br/e-sic/index.php?a=add'),
    ('Ipixuna do Pará - PA','ipixunadopara.pa.gov.br','ipixunadopara.pa.gov.br/e-sic/index.php?a=add'),
    ('Itaituba - PA','www.itaituba.pa.gov.br','www.itaituba.pa.gov.br/acessoainformacao/sic'),
    ('Itupiranga - PA','www.itupiranga.pa.gov.br','www.itupiranga.pa.gov.br/e_sic'),
    ('Jacundá - PA','www.jacunda.pa.gov.br','www.gdic.com.br/modulo/esic/login/4458489'),
    ('Juruti - PA','www.juruti.pa.gov.br','www.gdic.com.br/modulo/esic/login/4459487'),
    ('Marabá - PA','maraba.pa.gov.br','www.gdic.com.br/modulo/esic/login/4466490'),
    ('Marituba - PA','www.marituba.pa.gov.br/site','www.marituba.pa.gov.br/site/e-sic/index.php?a=add'),
    ('Moju - PA','moju.pa.gov.br','moju.pa.gov.br/solicitacoes/index.php?a=add&category=1'),
    ('Monte Alegre - PA','www.montealegre.pa.gov.br','www.montealegre.pa.gov.br/solicitar-informacao/'),
    ('Novo Repartimento - PA','www.novorepartimento.pa.gov.br/web','transparencia.novorepartimento.pa.gov.br/e-sic/?ent=1'),
    ('Óbidos - PA','obidos.pa.gov.br','obidos.pa.gov.br/solicitacoes/index.php?a=add&category=1'),
    ('Oriximiná - PA','www.oriximina.pa.gov.br','www.oriximina.pa.gov.br/sic.php'),
    ('Paragominas - PA','paragominas.pa.gov.br','paragominas.pa.gov.br/solicitacoes/index.php?a=add&category=1'),
    ('Parauapebas - PA','parauapebas.pa.gov.br','esic.parauapebas.pa.gov.br/index/'),
    ('Portel - PA','portel.pa.gov.br/portal','www.gdic.com.br/modulo/esic/login/4517486'),
    ('Redenção - PA','redencao.pa.gov.br','177.36.242.53:5656/transparencia/HomeESIC.aspx'),
    ('Rondon do Pará - PA','rondondopara.pa.gov.br/web','rondondopara.pa.gov.br/admt/e-sic/?ent=1'),
    ('Santa Isabel do Pará - PA','santaizabel.pa.gov.br','www.santaizabel.pa.gov.br/esic'),
    ('Santana do Araguaia - PA','www.pmsaraguaia.pa.gov.br/portal','www.pmsaraguaia.pa.gov.br/transparencia/acessoainformacao/solicitar'),
    ('Santarém - PA','www.santarem.pa.gov.br','portaltransparencia.santarem.pa.gov.br/02/servlet/esicfirst'),
    ('São Félix do Xingu - PA','www.sfxingu.pa.gov.br/web','transparencia.sfxingu.pa.gov.br/e-sic/?ent=1'),
    ('São Miguel do Guamá - PA','www.saomigueldoguama.pa.gov.br','www.gdic.com.br/modulo/esic/login/4570487'),
    ('Tomé-Açu - PA','prefeituratomeacu.pa.gov.br','prefeituratomeacu.pa.gov.br/e-sic/index.php?a=add'),
    ('Tucuruí - PA','tucurui.pa.gov.br','187.122.248.215:81/esic-tucurui/index/'),
    ('Ulianópolis - PA','149.47.148.233/~vcninjat/prefeitura','ulianopolis.pa.gov.br/e-sic2'),
    ('Vigia - PA','vigia.pa.gov.br','vigia.pa.gov.br/e-sic/index.php?a=add'),
    ('Macapá - AP','macapa.ap.gov.br','acessoainformacao.macapa.ap.gov.br/index/'),
    ('Santana - AP','santana.ap.gov.br','falacidadao.santana.ap.gov.br/index.php?getUndade=e-sic#tipo_manifestacao'),
    ('Araguaína - TO','www.araguaina.to.gov.br/portal','araguaina.prodataweb.inf.br/sig/app.html#/transparencia/e-sic/'),
    ('Gurupi - TO','www.gurupi.to.gov.br','www.gurupi.to.gov.br/transparencia/esic.php'),
    ('Porto Nacional - TO','www.portonacional.to.gov.br','www.portonacional.to.gov.br/index.php/e-sic'),
    ('Palmas - TO','www.palmas.to.gov.br','ouvidoria.palmas.to.gov.br/sic/'),
    ('Açailândia - MA','www.acailandia.ma.gov.br','www.acailandia.ma.gov.br/portal-cidadao/index.php?u=eyJwYXN0YSI6ImZ1bmNvZXNcL2NvbnRhXC9jYWRhc3Ryby5waHAifQ=='),
    ('Bacabal - MA','www.bacabal.ma.gov.br/portal','bacabal.ma.gov.br/transparencia/esic/'),
    ('Balsas - MA','www.balsas.ma.gov.br','transparencia.balsas.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Barra do Corda - MA','www.barradocorda.ma.gov.br/site','www.barradocorda.ma.gov.br/sic/index/'),
    ('Barreirinhas - MA','barreirinhas.ma.gov.br/site','www.transparenciadministrativa.com.br/portal/esic/pedidoCadastro.xhtml?token=38d02252aad6a8f42983ea3a8e1c6019edd1420e'),
    ('Buriticupu - MA','www.buriticupu.ma.gov.br','transparencia.buriticupu.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Chapadinha - MA','www.chapadinha.ma.gov.br','transparencia.chapadinha.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Coroatá - MA','www.coroata.ma.gov.br','transparencia.coroata.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Grajaú - MA','www.grajau.ma.gov.br','transparencia.grajau.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Imperatriz - MA','www.imperatriz.ma.gov.br','servicos.imperatriz.ma.gov.br/esic/index/'),
    ('Itapecuru Mirim - MA','www.itapecurumirim.ma.gov.br','transparencia.itapecurumirim.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Paço do Lumiar - MA','www.pacodolumiar.ma.gov.br','www.pacodolumiar.ma.gov.br/sic.php'),
    ('Pinheiro - MA','pinheiro.ma.gov.br','pinheiro.ma.gov.br/transparencia/public/acesso-a-informacao'),
    ('Santa Luzia - MA','santaluzia.ma.gov.br','transparencia.santaluzia.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('São José de Ribamar - MA','www.saojosederibamar.ma.gov.br','www.saojosederibamar.ma.gov.br/internauta/redir/origem/sic_cad'),
    ('São Luís - MA','www.saoluis.ma.gov.br','www.esic.saoluis.ma.gov.br/site/index.html?ReturnUrl=%2f'),
    ('Timon - MA','timon.ma.gov.br/site','162.144.204.169:8079/docs/HomeESIC.ASPX'),
    ('Tutóia - MA','www.tutoia.ma.gov.br','transparencia.tutoia.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Vargem Grande - MA','www.vargemgrande.ma.gov.br/portal','www.transparenciadministrativa.com.br/esic/index.xhtml?token=b4bd4e586c0a9ccb782ba50afe377fd7b1df0777'),
    ('Viana - MA','www.viana.ma.gov.br','transparencia.viana.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Zé Doca - MA','www.zedoca.ma.gov.br','transparencia.zedoca.ma.gov.br/sistemadeinformacao/esic/esic'),
    ('Floriano - PI','www.floriano.pi.gov.br','transparencia.floriano.pi.gov.br/floriano/acessoinformacao/pedidoinformacaocadastrar'),
    ('Parnaíba - PI','parnaiba.pi.gov.br/phb','170.80.82.42:8079/transparencia/'),
    ('Picos - PI','www2.picos.pi.gov.br','transparencia.picos.pi.gov.br:5655/Transparencia/'),
    ('Piripiri - PI','www.piripiri.pi.gov.br/site','200.98.143.125:8080/portaltransparencia/faces/sic/sic.xhtml'),
    ('Teresina - PI','pmt.pi.gov.br','esic.teresina.pi.gov.br/'),
    ('Acaraú - CE','www.acarau.ce.gov.br','www.acarau.ce.gov.br/sic.php'),
    ('Acopiara - CE','acopiara.ce.gov.br','www.acopiara.ce.gov.br/sic.php'),
    ('Aquiraz - CE','www.aquiraz.ce.gov.br','www.sac.aquiraz.ce.gov.br/home/#'),
    ('Aracati - CE','aracati.ce.gov.br','aracati.ce.gov.br/sic.php'),
    ('Beberibe - CE','beberibe.ce.gov.br','beberibe.ce.gov.br/sic.php'),
    ('Boa Viagem - CE','www.boaviagem.ce.gov.br','www.boaviagem.ce.gov.br/sic.php'),
    ('Camocim - CE','camocim.ce.gov.br','www.participar.com.br/camocim/users'),
    ('Canindé - CE','www.caninde.ce.gov.br','www.participar.com.br/caninde/users/sign_in'),
    ('Cascavel - CE','www.cascavel.ce.gov.br','www.cascavel.ce.gov.br/sic.php'),
    ('Caucaia - CE','www.caucaia.ce.gov.br','faleconosco.portalpmc.com.br/app_Login/'),
    ('Crateús - CE','www.crateus.ce.gov.br','esic.gtcontroller.com.br/crateus/index/'),
    ('Crato - CE','crato.ce.gov.br','participar.com.br/crato/users/sign_in'),
    ('Fortaleza - CE','www.fortaleza.ce.gov.br','acessoainformacao.fortaleza.ce.gov.br/sistema/Pessoa/CadastrarPessoa.aspx'),
    ('Granja - CE','www.granja.ce.gov.br','www.granja.ce.gov.br/sic.php'),
    ('Horizonte - CE','www.horizonte.ce.gov.br','www.participar.com.br/horizonte/users'),
    ('Icó - CE','www.ico.ce.gov.br','www.ico.ce.gov.br/sic.php'),
    ('Iguatu - CE','iguatu.ce.gov.br','iguatu.ce.gov.br/acesso-a-informacao/ouvidoria-iguatu/'),
    ('Itapagé - CE','itapaje.ce.gov.br','itapaje.ce.gov.br/sic.php'),
    ('Juazeiro do Norte - CE','www.juazeirodonorte.ce.gov.br','www.participar.com.br/juazeiro/users/sign_in'),
    ('Limoeiro do Norte - CE','limoeirodonorte.ce.gov.br','www.limoeirodonorte.ce.gov.br/sic.php'),
    ('Maranguape - CE','www.maranguape.ce.gov.br','www.maxcontrole.tudotransparente.com.br/maranguape/prefeitura/esic'),
    ('Morada Nova - CE','www.moradanova.ce.gov.br','www.MORADANOVA.CE.GOV.BR/ACESSOAINFORMACAO.PHP'),
    ('Pacajus - CE','www.pacajus.ce.gov.br','www.participar.com.br/pacajus/users/sign_in'),
    ('Pacatuba - CE','pacatuba.ce.gov.br','pacatuba.ce.gov.br/esic/index/'),
    ('Quixadá - CE','quixada.ce.gov.br','quixada.ce.gov.br/esic/'),
    ('Quixeramobim - CE','www.quixeramobim.ce.gov.br','www.quixeramobim.ce.gov.br/sic.php'),
    ('Russas - CE','russas.ce.gov.br','www.gdic.com.br/modulo/esic/principal/pub'),
    ('Sobral - CE','www.sobral.ce.gov.br','ouvidoria.sobral.ce.gov.br:8080/ouvidoria/cidadao/principal.jsf'),
    ('Tauá - CE','www.taua.ce.gov.br','www.gdic.com.br/modulo/esic/login/1439488'),
    ('Tianguá - CE','tiangua.ce.gov.br','tiangua.ce.gov.br/sic.php'),
    ('Trairi - CE','www.trairi.ce.gov.br','www.gdic.com.br/modulo/esic/login/1444488'),
    ('Viçosa do Ceará - CE','www.vicosa.ce.gov.br','www.vicosa.ce.gov.br/sic.php'),
    ('Açu - RN','assu.rn.gov.br','governotransparente.com/falacidadao/assu_rn/'),
    ('Caicó - RN','caico.rn.gov.br','caico.rn.gov.br/sic.php'),
    ('Parnamirim - RN','parnamirim.rn.gov.br','esic.parnamirim.rn.gov.br/index/'),
    ('Mossoró - RN','www.prefeiturademossoro.com.br','www.participar.com.br/mossoro/users/sign_in'),
    ('Natal - RN','natal.rn.gov.br','www.natal.rn.gov.br/leideacesso/index/'),
    ('São Gonçalo do Amarante - RN','saogoncalo.rn.gov.br','saogoncalo.rn.gov.br/e-sic/'),
    ('Cabedelo - PB','cabedelo.pb.gov.br','cabedelo.1doc.com.br/b.php?pg=wp/detalhes&itd=8'),
    ('Cajazeiras - PB','www.cajazeiras.pb.gov.br','cajazeiras.pb.gov.br/sic.php'),
    ('Campina Grande - PB','campinagrande.pb.gov.br','campinagrande.pb.gov.br/portal-da-transparencia/e-sic/'),
    ('Guarabira - PB','www.guarabira.pb.gov.br','www.guarabira.pb.gov.br/sic/'),
    ('João Pessoa - PB','www.joaopessoa.pb.gov.br','sic.joaopessoa.pb.gov.br/open.php?'),
    ('Patos - PB','patos.pb.gov.br','patos.pb.gov.br/servicos/acesso_a_informacao'),
    ('Santa Rita - PB','www.santarita.pb.gov.br','sic.santarita.pb.gov.br/index/'),
    ('Sapé - PB','www.sape.pb.gov.br','www.sape.pb.gov.br/e-sic.html'),
    ('Sousa - PB','www.sousa.pb.gov.br','www.sousa.pb.gov.br/sic.php'),
    ('Abreu e Lima - PE','abreuelima.pe.gov.br','abreuelima.pe.gov.br/e-sic/'),
    ('Araripina - PE','www.araripina.pe.gov.br','lisura.araripina.pe.gov.br/clientes/araripina_pm/portaltransparencia/?p=12&inicio=01/01/2020&fim=31/12/2020'),
    ('Arcoverde - PE','www.arcoverde.pe.gov.br','tenosoftsistemas.com.br/sgp/sic/?entidade=96'),
    ('Belo Jardim - PE','belojardim.pe.gov.br','belojardim.pe.gov.br/esiclivre/index/'),
    ('Bezerros - PE','bezerros.pe.gov.br','tenosoftsistemas.com.br/sgp/sic/'),
    ('Brejo da Madre de Deus - PE','www.brejomdeus.pe.gov.br','netuse.inf.br/brejo_m_deus/Transparencia/SolicitarInfo.aspx'),
    ('Buíque - PE','buique.pe.gov.br','staff.conceitofiscal.com.br/staff/cri/requerimento-informacao-cliente.xhtml?entidade=prefeiturabuique'),
    ('Cabo de Santo Agostinho - PE','servicos.cabo.pe.gov.br','servicos.cabo.pe.gov.br:8006/esic/'),
    ('Camaragibe - PE','www.camaragibe.pe.gov.br','transparencia.camaragibe.pe.gov.br/app/pe/camaragibe/1/e-sic'),
    ('Carpina - PE','carpina.pe.gov.br','tenosoftsistemas.com.br/portal/v81/sic/'),
    ('Caruaru - PE','caruaru.pe.gov.br','caruaru.pe.gov.br/portal-da-transparencia/e-sic/'),
    ('Escada - PE','www.escada.pe.gov.br','transparencia.escada.pe.gov.br/protocolos/novo'),
    ('Garanhuns - PE','garanhuns.pe.gov.br','esic.garanhuns.pe.gov.br/'),
    ('Goiana - PE','goiana.pe.gov.br','esic-rpps.com.br/?id=11155'),
    ('Gravatá - PE','www.prefeituradegravata.pe.gov.br','ouvidoriapmg.sistemacg.com.br/#!/menu/formulario/6'),
    ('Igarassu - PE','igarassu.pe.gov.br','staff.conceitofiscal.com.br/staff/cri/requerimento-informacao-cliente.xhtml?entidade=prefeituraigarassu'),
    ('Ipojuca - PE','www.ipojuca.pe.gov.br','s4.asp.srv.br:8380/einformacoes.pm.ipojuca.pe/servlet/einformacoes'),
    ('Jaboatão dos Guararapes - PE','jaboatao.pe.gov.br','eouve.com.br/esic/'),
    ('Limoeiro - PE','limoeiro.pe.gov.br','limoeiro.pe.gov.br/e-sic/'),
    ('Moreno - PE','moreno.pe.gov.br/portal1','179.124.141.226/esic/index/'),
    ('Olinda - PE','www.olinda.pe.gov.br','informacao.olinda.pe.gov.br/'),
    ('Ouricuri - PE','www.ouricuri.pe.gov.br/novosite','www.ouricuri.pe.gov.br/novosite/portaldatransparencia/e-sic-solicitar-informacao/'),
    ('Palmares - PE','palmares.pe.gov.br','transparencia.palmares.pe.gov.br/enviar-chamado/'),
    ('Paudalho - PE','www.paudalho.pe.gov.br/portal','143.137.216.35:5656/Transparencia/HomeESIC.aspx'),
    ('Paulista - PE','www.paulista.pe.gov.br/site','transparencia.paulista.pe.gov.br/codigos/web/lai/pedidoInformacaoForm.php'),
    ('Pesqueira - PE','pesqueira.pe.gov.br','pesqueira.1doc.com.br/b.php?pg=wp/detalhes&itd=7'),
    ('Petrolina - PE','petrolina.pe.gov.br','petrolina.pe.gov.br/portal-da-transparencia/e-sic/'),
    ('Recife - PE','www2.recife.pe.gov.br','transparencia.recife.pe.gov.br/codigos/web/lai/pedidoInformacaoForm.php'),
    ('Salgueiro - PE','www.salgueiro.pe.gov.br','tenosoftsistemas.com.br/sgp/sic/?entidade=468'),
    ('Santa Cruz do Capibaribe - PE','www.santacruzdocapibaribe.pe.gov.br','tenosoftsistemas.com.br/sgp/sic/?entidade=190'),
    ('São Bento do Una - PE','www.saobentodouna.pe.gov.br/v1','transparencia.saobentodouna.pe.gov.br/portal/v81/sic/sic.php?entidade=197'),
    ('São Lourenço da Mata - PE','slm.pe.gov.br','tenosoftsistemas.com.br/sgp/sic/?entidade=291'),
    ('Serra Talhada - PE','www.serratalhada.pe.gov.br','esic.serratalhada.pe.gov.br/index/'),
    ('Surubim - PE','www.surubim.pe.gov.br/site','177.153.18.155:8075/Transparencia/Default.aspx?AcessoIndividual=lnkESIC'),
    ('Timbaúba - PE','timbauba.pe.gov.br','tenosoftsistemas.com.br/sgp/sic/'),
    ('Arapiraca - AL','web.arapiraca.al.gov.br','e-sic.arapiraca.al.gov.br/solicitacao/nova'),
    ('Campo Alegre - AL','www.campoalegre.al.gov.br','www.municipioonline.com.br/al/prefeitura/campoalegre/cidadao/login'),
    ('Coruripe - AL','www.coruripe.al.gov.br','www.coruripe.al.gov.br/portal-da-transparencia-2/'),
    ('Delmiro Gouveia - AL','www.delmirogouveia.al.gov.br','www.pmdg.com.br/transparencia/index.php/acesso-a-informacao/solicitarinformacao'),
    ('Maceió - AL','www.maceio.al.gov.br','www2.informa.maceio.al.gov.br/esicsolicitante/pages/login.jsf'),
    ('Marechal Deodoro - AL','www.marechaldeodoro.al.gov.br','marechaldeodoro.leideacessoainformacao.com.br/novo/lai/sic'),
    ('Palmeira dos Índios - AL','palmeiradosindios.al.gov.br','lai.palmeiradosindios.al.gov.br/orgao/lai/sic'),
    ('Penedo - AL','penedo.al.gov.br','penedo.al.gov.br/e-sic/'),
    ('Rio Largo - AL','www.riolargo.al.gov.br','www.riolargo.al.gov.br/acesso-a-informacao'),
    ('São Miguel dos Campos - AL','www.saomigueldoscampos.al.gov.br','saomigueldoscampos.al.gov.br/esicsolicitar.html'),
    ('União dos Palmares - AL','transparencia.prefeiturauniaodospalmares.al.gov.br/transparenciaexecutiva/public/noticias','prefeiturauniaodospalmares.al.gov.br/'),
    ('Aracaju - SE','www.aracaju.se.gov.br','aracaju.1doc.com.br/b.php?pg=wp/detalhes&itd=7'),
    ('Lagarto - SE','www.lagarto.se.gov.br/v2','2.lagarto.se.gov.br/transparencia/'),
    ('Nossa Senhora do Socorro - SE','www.socorro.se.gov.br','esic.socorro.se.gov.br/index/'),
    ('São Cristóvão - SE','www.saocristovao.se.gov.br','www.municipioonline.com.br/se/prefeitura/saocristovao/cidadao/login'),
    ('Tobias Barreto - SE','tobiasbarreto.se.gov.br','tobiasbarreto.se.gov.br/servico-de-informacao-ao-cidadao-sic'),
    ('Alagoinhas - BA','www.alagoinhas.ba.gov.br','alagoinhas.ba.gov.br/esiclivre/cadastro/'),
    ('Araci - BA','www.araci.ba.gov.br','www.araci.ba.gov.br/Account/Login'),
    ('Barra - BA','barra.ba.gov.br','ba.acessoainformacao.org.br/prefeitura/barra/'),
    ('Barreiras - BA','barreiras.ba.gov.br','ctp.pmbarreiras.sudoesteinformatica.com.br/portal/'),
    ('Bom Jesus da Lapa - BA','www.bomjesusdalapa.ba.gov.br','www.bomjesusdalapa.ba.gov.br/e-sic/'),
    ('Brumado - BA','transparencia.brumado.ba.gov.br/stransparencia/Index/Index/0','www.brumado.ba.io.org.br/sic_novo/'),
    ('Caetité - BA','caetite.ba.gov.br','caetite.ba.gov.br/e-sic/sistema-e-sic/'),
    ('Camaçari - BA','www.camacari.ba.gov.br','municipioonline.com.br/ba/pmc/camacari/cidadao/login'),
    ('Campo Formoso - BA','campoformoso.ba.gov.br','campoformoso.ba.gov.br/transparencia/acesso-a-informacao/solicitar-informacao'),
    ('Candeias - BA','www.candeias.ba.io.org.br','sai.io.org.br/ba/candeias/site/esic'),
    ('Casa Nova - BA','www.casanova.ba.gov.br','www.casanova.ba.gov.br/servico-de-informacao-ao-cidadao'),
    ('Catu - BA','catu.ba.gov.br','www.acessoinformacao.com.br/sic/ba/catu'),
    ('Conceição do Coité - BA','conceicaodocoite.ba.gov.br/site','conceicaodocoite.ba.gov.br/sic/'),
    ('Cruz das Almas - BA','www.cruzdasalmas.ba.gov.br','187.87.205.198:5020/webrun/form.jsp?sys=TRP&action=openform&formID=8807&align=0&mode=- 1&goto=-1&filter=&scrolling=no'),
    ('Dias dÁvila - BA','www.diasdavila.ba.gov.br','www.municipioonline.com.br/ba/prefeitura/diasd-avila/cidadao/informacoes'),
    ('Euclides da Cunha - BA','www.euclidesdacunha.ba.gov.br','www.euclidesdacunha.ba.gov.br/contato'),
    ('Eunápolis - BA','eunapolis.ba.io.org.br','eunapolis.ba.io.org.br/sic_novo/'),
    ('Feira de Santana - BA','www.feiradesantana.ba.gov.br','www.transparencia.feiradesantana.ba.gov.br/?view=contato'),
    ('Guanambi - BA','www.guanambi.ba.gov.br','www.guanambi.ba.gov.br/e-sic/'),
    ('Ilhéus - BA','www.ilheus.ba.gov.br','transparencia.ilheus.ba.gov.br/internauta/redir/origem/sic_cad'),
    ('Ipirá - BA','ipira.ba.gov.br','www.ipira.ba.indap.com.br/esic/acesso'),
    ('Irecê - BA','irece.ba.gov.br','irece.ba.gov.br/e-sic/'),
    ('Itabuna - BA','www.itabuna.ba.gov.br','www.itabuna.ba.gov.br/esic.html'),
    ('Itamaraju - BA','itamaraju.ba.gov.br','www.acessoinformacao.com.br/ba/itamaraju/esic/?p=home'),
    ('Itapetinga - BA','www.itapetinga.ba.gov.br','acessoinformacao.org.br/ba/itapetinga/'),
    ('Jacobina - BA','www.jacobina.ba.gov.br','www.acessoinformacao.com.br/ba/jacobina/#sic'),
    ('Jaguaquara - BA','www.jaguaquara.ba.gov.br','www.jaguaquara.ba.io.org.br/sic_novo/'),
    ('Jequié - BA','www.jequie.ba.gov.br','pmjequie.ba.ipmbrasil.org.br/SIC/registrar-solicitacao'),
    ('Juazeiro - BA','www6.juazeiro.ba.gov.br','www.juazeiro.kinghost.net/app/transparencia/acesso_esic/acesso_esic.php'),
    ('Lauro de Freitas - BA','www.laurodefreitas.ba.gov.br/2019','laurodefreitas.ba.gov.br/novoesic/index/'),
    ('Luís Eduardo Magalhães - BA','luiseduardomagalhaes.ba.gov.br','ctppmlem.sudoesteinformatica.com.br/portal/'),
    ('Monte Santo - BA','www.montesanto.ba.gov.br','www.montesanto.ba.gov.br/site-2017/ouvidoria/index.html'),
    ('Paulo Afonso - BA','www.pauloafonso.ba.gov.br/novo','www.pauloafonso.ba.gov.br/acessoainformacao/'),
    ('Porto Seguro - BA','www.portoseguro.ba.gov.br','www.acessoinformacao.com.br/ba/portoseguro/esic/?p=novo-pedido'),
    ('Ribeira do Pombal - BA','ribeiradopombal.ba.gov.br','acessoinformacao.org.br/sic/ba/ribeiradopombal/pedidos/novo'),
    ('Salvador - BA','www.salvador.ba.gov.br','www.falasalvador.ba.gov.br/portal/portal/'),
    ('Santo Antônio de Jesus - BA','www.santoantoniodejesus.ba.io.org.br','www.santoantoniodejesus.ba.io.org.br/sic_novo/'),
    ('Senhor do Bonfim - BA','www.senhordobonfim.ba.gov.br','pmsb.emunicipio.com.br/pmsb/transparencia/transparencia_municipal.php?id_siga_orcamento_anual=10&acao=esic'),
    ('Serrinha - BA','www.serrinha.ba.gov.br/v2/index.php','www.serrinha.ba.gov.br/v2/index.php/transparencia/portt-10'),
    ('ões Filho - BA','oesfilho.ba.gov.br','oesfilho.ba.gov.br/acesso-a-informacao/'),
    ('Tucano - BA','www.tucano.ba.gov.br','acessoinformacao.org.br/ba/tucano/'),
    ('Vitória da Conquista - BA','www.pmvc.ba.gov.br','www.transparenciaconquista.ba.gov.br/sic/'),
    ('Alfenas - MG','www.alfenas.mg.gov.br','e-gov.betha.com.br/transparencia/01037-091/main.faces'),
    ('Barbacena - MG','barbacena.mg.gov.br/2','e-gov.betha.com.br/transparencia/01037-051/con_registropedidoinformacao.faces?mun=IdPgq9AFdnU='),
    ('Belo Horizonte - MG','prefeitura.pbh.gov.br','sso.acesso.gov.br/login?client_id=acesso.pbh.gov.br'),
    ('Betim - MG','www.betim.mg.gov.br','www.betim.mg.gov.br/sistema/site/index.html'),
    ('Bocaiúva - MG','www.prefeituradebocaiuva.com.br','transparencia.bocaiuva.mg.gov.br/Ocorrencia/Create'),
    ('Bom Despacho - MG','www.bomdespacho.mg.gov.br','bomdespacho.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Caratinga - MG','www.caratinga.mg.gov.br','www.caratinga.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Cataguases - MG','www.cataguases.mg.gov.br','cataguases.mg.gov.br.gestormunicipal.online/transparencia/e-sic/enviar-mensagem/'),
    ('Congonhas - MG','www.congonhas.mg.gov.br','www.congonhas.mg.gov.br/index.php/e-sic/'),
    ('Conselheiro Lafaiete - MG','conselheirolafaiete.mg.gov.br/v2','conselheirolafaiete.mg.gov.br/v1/ouvidoria/?page=sign-in&redirect_tohttp%3A%2F%2Fconselheirolafaiete.mg.gov.br%2Fv1%2Fouvidoria%2F%3Fdc%3D1591025319&dc=159'),
    ('Contagem - MG','www.contagem.mg.gov.br/novoportal','ouvidoria.brazilsouth.cloudapp.azure.com/sistema/site/index.html'),
    ('Coronel Fabriciano - MG','www.fabriciano.mg.gov.br','sistemas.fabriciano.mg.gov.br/portalcidadao/#075f539f0b7223f116d2c85c4ce1b1752fccb0db1fd92284312b33310fb199ef6050e9373e0f36365cbb7737a0e49e582e657146a648fd13f45185cb89587a94a882c2e1f92ec8ded37d6a1f362c0de87779a301a76ce67e7a0a2993e70876e3c193183efda'),
    ('Curvelo - MG','curvelo.mg.gov.br/site','amfcorrea.ddns.net/pmAgilNET/PGN/pgnLai.aspx'),
    ('Divinópolis - MG','www.divinopolis.mg.gov.br','177.69.246.151:8090/portalcidadao/#78c3e513dd43cb27d8a3e2f376196ffc656d7ea577b2c6fb63f5b21fd592a6e22d8461445 bd86f97c3571502fb5ff23fdb96c38dbcddce992c9428f22a470ccdaa0bdae32148c2355b1791b80f9f8e5ad22fad2c96786f6107afe0860 5e849f18ce217ed067e5ce3c80a7'),
    ('Esmeraldas - MG','www.esmeraldas.mg.gov.br','www.esmeraldas.mg.gov.br/ouvidoria/account.php?do=create'),
    ('Frutal - MG','www.frutal.mg.gov.br','esic.frutal.mg.gov.br/'),
    ('Governador Valadares - MG','www.valadares.mg.gov.br','www.valadares.mg.gov.br/solicitacao-de-informacao'),
    ('Guaxupé - MG','www.guaxupe.mg.gov.br','www.guaxupe.mg.gov.br/acesso-a-informacao'),
    ('Ibirité - MG','www.ibirite.mg.gov.br','www.ibirite.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Ipatinga - MG','www.ipatinga.mg.gov.br','www.ipatinga.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Itabira - MG','novoportal.itabira.mg.gov.br','esic.itabira.mg.gov.br/'),
    ('Itabirito - MG','www.itabirito.mg.gov.br','transparencia.itabirito.mg.gov.br/Ocorrencia/Create'),
    ('Itaúna - MG','www.itauna.mg.gov.br','www.itauna.mg.gov.br/portal/sic'),
    ('Ituiutaba - MG','www.ituiutaba.mg.gov.br','201.48.3.165:90/esic/#!/login'),
    ('João Monlevade - MG','pmjm.mg.gov.br','esic.portyx.com.br/esic/solicitacao/'),
    ('Juiz de Fora - MG','www.pjf.mg.gov.br','esic.pjf.mg.gov.br/'),
    ('Lagoa da Prata - MG','lagoadaprata.mg.gov.br','e-gov.betha.com.br/transparencia/01037-091/con_registropedidoinformacao.faces'),
    ('Lagoa Santa - MG','www.lagoasanta.mg.gov.br','esic.lagoasanta.mg.gov.br/index/'),
    ('Lavras - MG','pml.lavras.mg.gov.br','app.lavras.mg.gov.br/esic'),
    ('Leopoldina - MG','www.leopoldina.mg.gov.br','www.leopoldina.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Manhuaçu - MG','www.manhuacu.mg.gov.br','www.manhuacu.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Mariana - MG','www.mariana.mg.gov.br','e-gov.betha.com.br/transparencia/01037-091/con_registropedidoinformacao.faces?mun=f0oRtar6ScA='),
    ('Montes Claros - MG','portal.montesclaros.mg.gov.br','sis.montesclaros.mg.gov.br:81/site/index.html'),
    ('Muriaé - MG','muriae.mg.gov.br','transparencia.muriae.mg.gov.br/Ocorrencia/Create'),
    ('Nova Lima - MG','novalima.mg.gov.br','www.tag.pnl.mg.gov.br/'),
    ('Nova Serrana - MG','www.novaserrana.mg.gov.br','transparencia.novaserrana.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Ouro Preto - MG','www.ouropreto.mg.gov.br','e-sic.ouropreto.mg.gov.br/esic/index.php?page=informacao'),
    ('Paracatu - MG','www.paracatu.mg.gov.br','200.149.134.10/portalcidadao/#971adfa449daa07f8f7ce159f7fa9053dd1121dd8cbd8d8353890d4ada6b1ca844be3a8f058617108191d8d7b6f32f842c797bebe8bf0a756fe85033f3adc2a2ce0d9cd6428a66e212c572e26e028786db7e06bf38232bd97d992a7080d616133c126ddff6aed7516a8ed7af7e'),
    ('Pará de Minas - MG','parademinas.mg.gov.br','parademinas.mg.gov.br/ouvidoria/'),
    ('Passos - MG','www.passos.mg.gov.br/pages','www.passos.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Patos de Minas - MG','patosdeminas.mg.gov.br/home','www.transparencia.patosdeminas.mg.gov.br/paginas/publico/lei12527/homeAcessoInformacao.xhtml'),
    ('Patrocínio - MG','www.portal.patrocinio.mg.gov.br/pm','201.16.156.251:8085/Form/e_sic/HomeAcessoInformacao'),
    ('Pedro Leopoldo - MG','pedroleopoldo.mg.gov.br','cidadao.pedroleopoldo.mg.gov.br:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a5660848a422c1230e7e3809691f10f1966a7a0baa08d4d1542f8c592a1edba9da1de89411186067f942110102e29c7e66280c3a47fd280dc70fc61624fc7a4dffeeef0e9c149080088d96bdbc58141cb9d7331bf'),
    ('Poços de Caldas - MG','pocosdecaldas.mg.gov.br','200.195.60.13:8081/portalcidadao/#78c3e513dd43cb27d8a3e2f376196ffc656d7ea577b2c6fb7c32655c9cd9a1%C4%B38a752 6355969%C5%A4%C4%B80f4862877ea%C4%B7f9cf667add0647ae31c61d7848ed49deaaee2625c6c8d963bbe087f2376b5ccea7e838 763a6ce7696d614969200d1007faed55ddd'),
    ('Ponte Nova - MG','www.pontenova.mg.gov.br','www.pontenova.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Pouso Alegre - MG','pousoalegre.mg.gov.br','pousoalegre.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Ribeirão das Neves - MG','www.ribeiraodasneves.mg.gov.br','www.ribeiraodasneves.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('São Francisco - MG','www.prefeituradesaofrancisco.mg.gov.br','www.prefeituradesaofrancisco.mg.gov.br/e-sic/'),
    ('São João del Rei - MG','www.saojoaodelrei.mg.gov.br','esic.saojoaodelrei.mg.gov.br/'),
    ('São Sebastião do Paraíso - MG','www.ssparaiso.mg.gov.br','transparencia.ssparaiso.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Sete Lagoas - MG','www.setelagoas.mg.gov.br','www.setelagoas.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Timóteo - MG','www.timoteo.mg.gov.br','transparencia.timoteo.mg.gov.br/internauta/redir/origem/sic_cad'),
    ('Três Corações - MG','www.trescoracoes.mg.gov.br','esic.trescoracoes.mg.gov.br/index/'),
    ('Três Pontas - MG','www.trespontas.mg.gov.br','www.trespontas.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Ubá - MG','www.uba.mg.gov.br','www.uba.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Uberaba - MG','www.uberaba.mg.gov.br/portal','www.uberaba.mg.gov.br/sic/#login'),
    ('Uberlândia - MG','www.uberlandia.mg.gov.br','www.uberlandia.mg.gov.br/portal-da-transparencia/atendimento-ao-publico/atendimento-ao-publico/'),
    ('Unaí - MG','www.prefeituraunai.mg.gov.br','www.prefeituraunai.mg.gov.br/pmu/index.php/e-sic.html'),
    ('Varginha - MG','www.varginha.mg.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3170701,1'),
    ('Vespasiano - MG','www.vespasiano.mg.gov.br','esic.vespasiano.mg.gov.br/Ocorrencia/Create'),
    ('Viçosa - MG','www.vicosa.mg.gov.br','www.vicosa.mg.gov.br/servico-de-informacao-ao-cidadao'),
    ('Aracruz - ES','www.aracruz.es.gov.br','sistema.ouvidorias.gov.br/publico/ES/ARACRUZ/Manifestacao/RegistrarManifestacao'),
    ('Cachoeiro de Itapemirim - ES','www.cachoeiro.es.gov.br/novocoronavirus','fala.cachoeiro.es.gov.br:8443/CadastroChamados.aspx?idTipo=3'),
    ('Cariacica - ES','www.cariacica.es.gov.br','transparencia.cariacica.es.gov.br/Pedido.Cadastro.aspx?tipoId=8'),
    ('Colatina - ES','www.colatina.es.gov.br/acidade','www.colatina.es.gov.br/ti/?pagina=ouvidoria'),
    ('Guarapari - ES','www.guarapari.es.gov.br','www.guarapari.es.gov.br/e-sic'),
    ('Linhares - ES','linhares.es.gov.br','esic.linhares.es.gov.br/site/index.html?ReturnUrl=%2f'),
    ('Nova Venécia - ES','www.novavenecia.es.gov.br','www.novavenecia.es.gov.br/e-sic/'),
    ('São Mateus - ES','www.saomateus.es.gov.br','www.saomateus.es.gov.br/acesso-a-informacao'),
    ('Serra - ES','www.serra.es.gov.br','transparencia.serra.es.gov.br/esic.aspx'),
    ('Viana - ES','www.viana.es.gov.br','e-sic.viana.es.gov.br/sistema/site/index.html'),
    ('Vila Velha - ES','www.vilavelha.es.gov.br','sistemas.vilavelha.es.gov.br/ouvidoria/CadastrarEvento.aspx?tipo_evento=7'),
    ('Vitória - ES','www.vitoria.es.gov.br','sistemas.vitoria.es.gov.br/sic/aberto/lai/?from=pmv'),
    ('Angra dos Reis - RJ','www.angra.rj.gov.br','www.angra.rj.gov.br/sic.asp?indexsigla=transp'),
    ('Araruama - RJ','www.araruama.rj.gov.br/novo','www.araruama.rj.gov.br/esiclivre/index/'),
    ('Barra do Piraí - RJ','www.barradopirai.rj.gov.br/portal','e-gov.betha.com.br/transparencia/01037-048/con_registropedidoinformacao.faces'),
    ('Barra Mansa - RJ','www.barramansa.rj.gov.br','sistema.ouvidorias.gov.br/publico/RJ/BARRAMANSA/Manifestacao/RegistrarManifestacao'),
    ('Cabo Frio - RJ','cabofrio.rj.gov.br','cabofrio.aexecutivo.com.br/sic.php'),
    ('Cachoeiras de Macacu - RJ','www.cachoeirasdemacacu.rj.gov.br','www.cachoeirasdemacacu.rj.gov.br/'),
    ('Campos dos Goytacazes - RJ','www.campos.rj.gov.br','sistemas.campos.rj.gov.br/sic/open.php?V=SOLICITA%C3%87%C3%83O%20DE%20INFORMA%C3%87%C3%95'),
    ('Duque de Caxias - RJ','www.duquedecaxias.rj.gov.br','sistema.ouvidorias.gov.br/publico/RJ/Duquedecaxias/Manifestacao/RegistrarManifestacao'),
    ('Itaguaí - RJ','itaguai.rj.gov.br','itaguai.rj.gov.br/esic/index/'),
    ('Japeri - RJ','www.japeri.rj.gov.br/japeri','131.221.133.100/pmjaperi/websis/portal_transparencia/financeiro/contas_publicas/index.php?consulta=sic'),
    ('Macaé - RJ','www.macae.rj.gov.br','sistemas.macae.rj.gov.br:84/esic/index/'),
    ('Magé - RJ','mage.rj.gov.br','transparencia.mage.rj.gov.br/acessoainformacao/'),
    ('Maricá - RJ','www.marica.rj.gov.br','esic.marica.rj.gov.br/index/'),
    ('Mesquita - RJ','www.mesquita.rj.gov.br/pmm','transparencia.mesquita.rj.gov.br/'),
    ('Nilópolis - RJ','nilopolis.rj.gov.br/site','siap.nilopolis.rj.gov.br:8082/pmnilopolis/websis/portal_transparencia/financeiro/contas_publicas/index.php?co nsulta=sic'),
    ('Niterói - RJ','www.niteroi.rj.gov.br','transparencia.niteroi.rj.gov.br/Acesso-a-Informacao/acesso-a-informacao.html'),
    ('Nova Iguaçu - RJ','www.novaiguacu.rj.gov.br','dstec.info/esiclivre/cadastro/'),
    ('Paracambi - RJ','paracambi.rj.gov.br','paracambi.ccanet.com.br/transparencia/pedidoacessoinformacao/solicitacaoinformacao?entidade=1'),
    ('Petrópolis - RJ','www.petropolis.rj.gov.br/pmp','www.petropolis.rj.gov.br/e-gov/gap/e-sic/index/'),
    ('Queimados - RJ','www.queimados.rj.gov.br','www.queimados.rj.gov.br/portal/esic/login'),
    ('Resende - RJ','resende.rj.gov.br','esic.resende.rj.gov.br/sistema/site/index.html?ReturnUrl=%2fsistema%2fsite%2f'),
    ('Rio Bonito - RJ','www.riobonito.rj.gov.br','e-gov.betha.com.br/transparencia/01037-091/con_registropedidoinformacao.faces'),
    ('Rio de Janeiro - RJ','prefeitura.rio','www.1746.rio/portal/cadastro'),
    ('São João de Meriti - RJ','meriti.rj.gov.br/home','transparencia.meriti.rj.gov.br/'),
    ('São Pedro da Aldeia - RJ','pmspa.rj.gov.br/home','transparencia.pmspa.rj.gov.br/'),
    ('Saquarema - RJ','www.saquarema.rj.gov.br','esic.saquarema.rj.gov.br/index/'),
    ('Seropédica - RJ','www.seropedica.rj.gov.br','www.seropedica.rj.gov.br/'),
    ('Teresópolis - RJ','teresopolis.rj.gov.br','teresopolis.rj.gov.br/secretarias/ogm/'),
    ('Três Rios - RJ','www.tresrios.rj.gov.br','pmtresic.fgmaiss.com.br/'),
    ('Valença - RJ','www.valenca.rj.gov.br','e-gov.betha.com.br/transparencia/01037-091/con_registropedidoinformacao.faces?mun=hIoztZTQAPPf3HtU3wSZ8P5OLzEuXYwR'),
    ('Volta Redonda - RJ','new.voltaredonda.rj.gov.br','www.portalvr.com/esic/index/'),
    ('Americana - SP','www.americana.sp.gov.br','esic.americana.sp.gov.br/esic_index.php?p=login'),
    ('Amparo - SP','www.amparo.sp.gov.br','amparogpm.presconinformatica.com.br/ords/gpmodamp/f?p=205:100210:::::p0_entidade:1'),
    ('Andradina - SP','www.andradina.sp.gov.br','www.andradina.sp.gov.br/portal/sic'),
    ('Araçatuba - SP','www.aracatuba.sp.gov.br','s4.asp.srv.br:8380/einformacoes.pm.aracatuba.sp/servlet/einformacoes'),
    ('Araraquara - SP','www.araraquara.sp.gov.br','www.leidainformacao.com.br/ords/portal/f?p=151:LOGIN:6437736312062'),
    ('Araras - SP','araras.sp.gov.br/home','araras.sp.gov.br/portal/acesso/'),
    ('Artur Nogueira - SP','www.arturnogueira.sp.gov.br','www.arturnogueira.sp.gov.br/comunicacao/'),
    ('Arujá - SP','prefeituradearuja.sp.gov.br','www.prefeituradearuja.sp.gov.br/esiclivre/index/'),
    ('Assis - SP','www.assis.sp.gov.br','www.assis.sp.gov.br/esic'),
    ('Atibaia - SP','www.prefeituradeatibaia.com.br','www.atibaia.sp.gov.br/esic/'),
    ('Barretos - SP','www.barretos.sp.gov.br','s4.asp.srv.br:8380/einformacoes.pm.barretos.sp/servlet/einformacoes'),
    ('Barueri - SP','portal.barueri.sp.gov.br','portal.barueri.sp.gov.br/cidadao/acesso-a-informacao'),
    ('Batatais - SP','www.batatais.sp.gov.br','leideacesso.etransparencia.com.br/batatais.prefeitura.sp/'),
    ('Bauru - SP','www2.bauru.sp.gov.br','www2.bauru.sp.gov.br/sist_documentos/cadastrar.aspx?a=115'),
    ('Bebedouro - SP','www.bebedouro.sp.gov.br/portal','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3506102,1'),
    ('Bertioga - SP','www.bertioga.sp.gov.br','e-sic.bertioga.sp.gov.br:90/esic/#!/login'),
    ('Birigui - SP','www.birigui.sp.gov.br/birigui','152.67.39.53:3000/?cod=14'),
    ('Boituva - SP','www.boituva.sp.gov.br','leideacesso.sistemas4r.com.br/login.aspx?3D6C1A9CC03FE480CFA1C96007F7D14F'),
    ('Botucatu - SP','www.botucatu.sp.gov.br','smarapd.botucatu.sp.gov.br/esic/#!/login'),
    ('Bragança Paulista - SP','braganca.sp.gov.br','eouve.com.br/'),
    ('Caçapava - SP','cacapava.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3508504,1'),
    ('Caieiras - SP','www.caieiras.sp.gov.br','leideacesso.etransparencia.com.br/caieiras.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Cajamar - SP','cajamar.sp.gov.br','e-ouvidoria.cajamar.sp.gov.br/index.php?a=add&category=12'),
    ('Campinas - SP','www.campinas.sp.gov.br','esic.campinas.sp.gov.br/index/'),
    ('Campo Limpo Paulista - SP','www.campolimpopaulista.sp.gov.br','campolimpopaulista.sp.gov.br/e-sic/esic-campo-limpo-paulista.php'),
    ('Campos do Jordão - SP','www.camposdojordao.sp.gov.br','camposdojordaogpm.presconinformatica.com.br/ords/gpmodcjd/f?p=205:100210:::::P0_ENTIDADE:3'),
    ('Caraguatatuba - SP','www.caraguatatuba.sp.gov.br','ouvidoria.caraguatatuba.sp.gov.br/manifestacao/nova'),
    ('Cosmópolis - SP','cosmopolis.sp.gov.br','cosmopolis.sp.gov.br/fale-conosco/'),
    ('Cotia - SP','www.cotia.sp.gov.br','leideacesso.etransparencia.com.br/cotia.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Cruzeiro - SP','www.cruzeiro.sp.gov.br/page','pmcruzeiro.ddns.net:8081/pmcruzeiro/websis/portal_transparencia/financeiro/contas_publicas/index.php?consulta=sic'),
    ('Cubatão - SP','www.cubatao.sp.gov.br','esic.cubatao.sp.gov.br/site/index.html?ReturnUrl=%2f'),
    ('Diadema - SP','www.diadema.sp.gov.br','www.diadema.sp.gov.br/lei-de-acesso-a-informacao'),
    ('Embu-Guaçu - SP','embuguacu.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3515103,1'),
    ('Fernandópolis - SP','www.fernandopolis.sp.gov.br','servicos1.fernandopolis.sp.gov.br:5656/transparencia/HomeEsic.aspx'),
    ('Ferraz de Vasconcelos - SP','ferrazdevasconcelos.sp.gov.br/web','leideacesso.etransparencia.com.br/ferrazdevasconcelos.prefeitura.sp/tdaportalclient.aspx'),
    ('Franca - SP','www.franca.sp.gov.br','www.franca.sp.gov.br/portal-transparencia/paginas/publica/pedido_informacao_pedido.xhtml'),
    ('Francisco Morato - SP','www.franciscomorato.sp.gov.br','esic.franciscomorato.sp.gov.br'),
    ('Guaratinguetá - SP','guaratingueta.sp.gov.br','siap.guaratingueta.sp.gov.br:8443/pmguaratingueta/websis/portal_transparencia/financeiro/contas_publicas/index.php?consulta=sic'),
    ('Guarujá - SP','www.guaruja.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3518701,1'),
    ('Guarulhos - SP','www.guarulhos.sp.gov.br','portaltransparencia.guarulhos.sp.gov.br/acesso-a-informacao/solicita%C3%A7%C3%A3o-de-informa%C3%A7%C3%A3o'),
    ('Ibitinga - SP','www.ibitinga.sp.gov.br','www.ibitinga.sp.gov.br/portal-transparencia/#'),
    ('Indaiatuba - SP','www.indaiatuba.sp.gov.br','www.indaiatuba.sp.gov.br/esic/'),
    ('Itanhaém - SP','www2.itanhaem.sp.gov.br','www.itanhaem.sp.gov.br/esic/index/'),
    ('Itapecerica da Serra - SP','www.itapecerica.sp.gov.br','leideacesso.etransparencia.com.br/itapecericadaserra.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Itapetininga - SP','www.itapetininga.sp.gov.br','www.itapetininga.sp.gov.br/sic-servico-de-informacao-ao-cidadao/'),
    ('Itapeva - SP','www.itapeva.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3522406,1'),
    ('Itapevi - SP','itapevi.sp.gov.br','leideacesso.etransparencia.com.br/itapevi.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Itapira - SP','itapira.sp.gov.br','transparencia.itapira.sp.gov.br:8079/Transparencia/'),
    ('Itaquaquecetuba - SP','www.itaquaquecetuba.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3523107,1'),
    ('Itararé - SP','mbt.cgu.gov.br/publico','www.itarare.sp.gov.br/formulario-requerimento-acesso-a-informacao/'),
    ('Itatiba - SP','www.itatiba.sp.gov.br','portal.itatiba.sp.gov.br/portalsic'),
    ('Itu - SP','itu.sp.gov.br','leideacesso.etransparencia.com.br/itu.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Itupeva - SP','itupeva.sp.gov.br/site','eouve.com.br/'),
    ('Jaboticabal - SP','www.jaboticabal.sp.gov.br','transparencia.jaboticabal.sp.gov.br/#esic'),
    ('Jacareí - SP','www.jacarei.sp.gov.br','esic.jacarei.sp.gov.br/'),
    ('Jaguariúna - SP','www.jaguariuna.sp.gov.br/atendimento','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3524709,1'),
    ('Jandira - SP','www.jandira.sp.gov.br','200.98.169.8/transparencia/(S(3v24s33ldhjr2schp15mwsxm),),/web_esic_consulta.aspx?id=13'),
    ('Jaú - SP','www.jau.sp.gov.br','leideacesso.etransparencia.com.br/jahu.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Jundiaí - SP','jundiai.sp.gov.br','jundiai.sp.gov.br/lei-de-acesso-a-informacao/'),
    ('Leme - SP','www.leme.sp.gov.br','esicnew.leme.grupohdc.com.br/index/'),
    ('Lençóis Paulista - SP','www2.lencoispaulista.sp.gov.br/v2','leideacesso.etransparencia.com.br/lencoispaulista.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Limeira - SP','www.limeira.sp.gov.br/sitenovo','leideacesso.etransparencia.com.br/limeira.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Lins - SP','www.lins.sp.gov.br','s4.asp.srv.br:8380/einformacoes.pm.lins.sp/servlet/einformacoes'),
    ('Lorena - SP','www.lorena.sp.gov.br/wordpress','www.lorena.sp.gov.br/sic/fisico'),
    ('Mairiporã - SP','www.mairipora.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3528502,1'),
    ('Marília - SP','www.marilia.sp.gov.br','www3.marilia.sp.gov.br/esic/#!/login'),
    ('Matão - SP','novo.matao.sp.gov.br','transparencia.matao.sp.gov.br/?cod=19'),
    ('Mauá - SP','maua.sp.gov.br','www.maua.sp.gov.br/AcessoInformacao.aspx'),
    ('Mirassol - SP','www.mirassol.sp.gov.br','www.mirassol.sp.gov.br/sic/'),
    ('Mococa - SP','portal.mococa.sp.gov.br/principal','e-gov.betha.com.br/transparencia/01037-048/recursos.faces?mun=hmUX2QLFs6PsX6LuoN3DQf0fn3kyD05Q'),
    ('Mogi das Cruzes - SP','www.mogidascruzes.sp.gov.br','www.transparencia.pmmc.com.br/fale-conosco'),
    ('Mogi Guaçu - SP','www.mogiguacu.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3530706,1'),
    ('Moji-Mirim - SP','www.mogimirim.sp.gov.br','187.92.42.98:9090/Transparencia/Questao/Escolha'),
    ('Mongaguá - SP','mongagua.sp.gov.br','webnetserver.com.br/prefeituramongagua/formulario-e-sic'),
    ('Nova Odessa - SP','www.novaodessa.sp.gov.br','smarportal.novaodessa.sp.gov.br:3001/?cod=14'),
    ('Olímpia - SP','www.olimpia.sp.gov.br','remoto.olimpia.sp.gov.br:90/esic/#!/login'),
    ('Osasco - SP','www.osasco.sp.gov.br','e-sic.osasco.sp.gov.br/'),
    ('Ourinhos - SP','www.ourinhos.sp.gov.br','protocolo.ourinhos.sp.gov.br/falacidadao/#!/criarconta'),
    ('Penápolis - SP','www.penapolis.sp.gov.br','www.penapolis.sp.gov.br/portal/sic'),
    ('Peruíbe - SP','www.peruibe3.sp.gov.br/boletim-oficial','eouve.com.br/'),
    ('Piedade - SP','www.piedade.sp.gov.br','www.piedade.sp.gov.br/portal/sic'),
    ('Pindamonhangaba - SP','siapegov.pindamonhangaba.sp.gov.br/portal-transparencia','eouve.com.br/ocorrencias/ epindamonhangaba.1doc.com.br/b.php?pg=wp/detalhes&itd=7'),
    ('Piracicaba - SP','www.piracicaba.sp.gov.br','sistemas.pmp.sp.gov.br/smg/SIC/control_login_a/'),
    ('Pirassununga - SP','pirassununga.sp.gov.br','esic.pirassununga.sp.gov.br'),
    ('Poá - SP','prefeituradepoa.sp.gov.br','leideacesso.etransparencia.com.br/poa.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Porto Feliz - SP','www.portofeliz.sp.gov.br','leideacesso.sistemas4r.com.br/login.aspx?6EB7932AE6529B9FC36350664B4B09EC'),
    ('Praia Grande - SP','www.praiagrande.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3541000,1'),
    ('Presidente Prudente - SP','www.presidenteprudente.sp.gov.br/site','www.presidenteprudente.sp.gov.br/transparencia/lai/lai.xhtml'),
    ('Registro - SP','www.registro.sp.gov.br','www.registro.sp.gov.br/transparencia/form.asp'),
    ('Ribeirão Pires - SP','www.ribeiraopires.sp.gov.br','200.168.239.234:65000/?cod=14'),
    ('Ribeirão Preto - SP','www.ribeiraopreto.sp.gov.br/portal','www.ribeiraopreto.sp.gov.br/J324/index.xhtml'),
    ('Rio Claro - SP','www.rioclaro.sp.gov.br','leideacesso.etransparencia.com.br/rioclaro.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Salto - SP','salto.sp.gov.br','cidadaosalto.meumunicipio.digital/apex/salto01/f?p=331:22:::NO:::'),
    ('Santa Bárbara dOeste - SP','www.santabarbara.sp.gov.br/v5','enzo.santabarbara.sp.gov.br/v5/acessoainformacao/index.php'),
    ('Santa Isabel - SP','santaisabel.sp.gov.br/portal','eouve.com.br/sic/'),
    ('Santana de Parnaíba - SP','www.santanadeparnaiba.sp.gov.br','intranet.santanadeparnaiba.sp.gov.br/e-SIC-PUB/'),
    ('Santo André - SP','www2.santoandre.sp.gov.br','www.santoandre.sp.gov.br/PortalServico/Seguranca/frmLogin.aspx'),
    ('Santos - SP','www.santos.sp.gov.br','egov1.santos.sp.gov.br/sicweb/'),
    ('São Bernardo do Campo - SP','www.saobernardo.sp.gov.br','www.saobernardo.sp.gov.br/web/transparencia/acesso-a-informacao'),
    ('São Caetano do Sul - SP','www.saocaetanodosul.sp.gov.br','esic.saocaetanodosul.sp.gov.br/'),
    ('São Carlos - SP','www.saocarlos.sp.gov.br','www.leidainformacao.com.br/ords/portal/f?p=151:LOGIN:6697417167192'),
    ('São João da Boa Vista - SP','saojoao.sp.gov.br','eouve.com.br/'),
    ('São Joaquim da Barra - SP','www.saojoaquimdabarra.sp.gov.br/site','eouve.com.br/esic/'),
    ('São José do Rio Pardo - SP','saojosedoriopardo.sp.gov.br','www.sicmunicipal.com.br/#2'),
    ('São José do Rio Preto - SP','www.riopreto.sp.gov.br','www.riopreto.sp.gov.br/portaltransparencia/hometransparencia'),
    ('São José dos Campos - SP','www.sjc.sp.gov.br','central156.ipplan.org.br/protocolo'),
    ('São Paulo - SP','www.capital.sp.gov.br','esic.prefeitura.sp.gov.br/Account/Login.aspx'),
    ('São Roque - SP','www.saoroque.sp.gov.br','sistemas.saoroque.sp.gov.br/portalcidadao/#075f539f0b7223f116d2c85c4ce1b1752fccb0db1fd92284312b33310fb199ef6050 e9373e0f36365cbb7737a0e49e582e657146a648fd13f45185cb89587a94a882c2e1f92ec8ded37d6a1f362c0de87779a301a76ce67e7a 0a2993e70876e3c193183efda30'),
    ('São Sebastião - SP','www.saosebastiao.sp.gov.br','www.saosebastiao.sp.gov.br/esic/index/'),
    ('São Vicente - SP','www.saovicente.sp.gov.br/publico','online.saovicente.sp.gov.br/pmsaovicente/websis/siapegov/administrativo/aten/aten_valida.php'),
    ('Sertãozinho - SP','sertaozinho.sp.gov.br','portaltransparencia.sertaozinho.sp.gov.br:3000/?cod=74'),
    ('Sumaré - SP','sumare.atende.net/#!/tipo','sumare.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Taboão da Serra - SP','ts.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3552809,1'),
    ('Taquaritinga - SP','taquaritinga.sp.gov.br','leideacesso.etransparencia.com.br/esic/wp_login.aspx?3553708,1'),
    ('Tatuí - SP','www2.tatui.sp.gov.br','eouve.com.br/sic/'),
    ('Taubaté - SP','www.taubate.sp.gov.br','leideacesso.etransparencia.com.br/taubate.prefeitura.sp/TDAPortalClient.aspx?414'),
    ('Tupã - SP','www.tupa.sp.gov.br','www.tupa.sp.gov.br/informacaosic.php'),
    ('Ubatuba - SP','www.ubatuba.sp.gov.br','www.ubatuba.sp.gov.br/sic/eletronico'),
    ('Valinhos - SP','www.valinhos.sp.gov.br','179.108.81.10:90/esic/#!/login'),
    ('Vargem Grande Paulista - SP','www.vargemgrandepta.sp.gov.br','www.vargemgrandepta.sp.gov.br/acesso-a-informacao/esic/index/'),
    ('Várzea Paulista - SP','portal.varzeapaulista.sp.gov.br','www2.varzeapaulista.sp.gov.br/portalcidadao/'),
    ('Votorantim - SP','www.votorantim.sp.gov.br','www.votorantim.sp.gov.br/portal/sic'),
    ('Votuporanga - SP','votuporanga.sp.gov.br/n/home','web.votuporanga.sp.gov.br:5656/Transparencia/'),
    ('Almirante Tamandaré - PR','tamandare.pr.gov.br','e-gov.betha.com.br/transparencia/01037-054/con_registropedidoinformacao.faces'),
    ('Apucarana - PR','www.apucarana.pr.gov.br/site','sys.apucarana.pr.gov.br/apucarana-pr/protocolo_fw/controle/protocolo_web_login.php'),
    ('Arapongas - PR','www.arapongas.pr.gov.br','arapongas.atende.net/#!/tipo/acesso-informacao/valor/solicitar-acesso'),
    ('Araucária - PR','araucaria.atende.net','araucaria.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Cambé - PR','www.cambe.pr.gov.br/site','sistema.cambe.pr.gov.br:8082/ouvidoria/orgaos/123/fale_ouvidor.php'),
    ('Campo Largo - PR','www.campolargo.pr.gov.br','campolargo.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1'),
    ('Campo Mourão - PR','campomourao.atende.net','campomourao.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Cascavel - PR','cascavel.atende.net','cascavel.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/0/'),
    ('Castro - PR','castro.atende.net','castro.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1'),
    ('Cianorte - PR','www.cianorte.pr.gov.br','ip.cianorte.pr.gov.br:8082/portaltransparencia/esic'),
    ('Colombo - PR','www.colombo.pr.gov.br','colombo.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Fazenda Rio Grande - PR','www.fazendariogrande.pr.gov.br','www.fazendariogrande.pr.gov.br/transparencia/geral/portal-de-acesso-a-informacao'),
    ('Foz do Iguaçu - PR','www5.pmfi.pr.gov.br','www2.pmfi.pr.gov.br/giig/portais/portaldatransparencia/AcessoInformacao/wfrmAcessoInformacaoSolicitacao. aspx'),
    ('Francisco Beltrão - PR','www.franciscobeltrao.pr.gov.br','www.franciscobeltrao.pr.gov.br/lei-de-acesso-a-informacao/formulario-acesso-a-informacao/'),
    ('Guarapuava - PR','www.guarapuava.pr.gov.br','www.pmg.pr.gov.br/ouvidoria/index.php'),
    ('Ibiporã - PR','www.ibipora.pr.gov.br','portaltransparencia.ibipora.pr.gov.br/home/fale-conosco'),
    ('Irati - PR','irati.pr.gov.br','transparencia.irati.pr.gov.br:8086/protocolo/ouvidoria'),
    ('Londrina - PR','www.londrina.pr.gov.br','sei.londrina.pr.gov.br/sei/controlador_externo.php?acao=ouvidoria&id_orgao_acesso_externo=0'),
    ('Marechal Cândido Rondon - PR','marechalcandidorondon.atende.net','marechalcandidorondon.atende.net/#!/tipo/acesso-informacao/'),
    ('Maringá - PR','www2.maringa.pr.gov.br/site','venus.maringa.pr.gov.br:8090/portaltransparencia/esic'),
    ('Paranaguá - PR','www.paranagua.pr.gov.br','paranagua.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Paranavaí - PR','www.paranavai.pr.gov.br','www.ingadigital.com.br/transparencia/index.php?sessao=fe1a1d0353uvfe&id_cliente=12101'),
    ('Pato Branco - PR','www.patobranco.pr.gov.br','patobranco.pr.gov.br/fala-cidadao/'),
    ('Pinhais - PR','www.pinhais.pr.gov.br/governo','pinhais.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Piraquara - PR','www.piraquara.pr.gov.br','sistemas.piraquara.pr.gov.br:8093/portaltransparencia/esic'),
    ('Ponta Grossa - PR','pontagrossa.pr.gov.br','servicos.pontagrossa.pr.gov.br/portaltransparencia/esic'),
    ('Prudentópolis - PR','www.prudentopolis.pr.gov.br','esic.portyx.com.br/esic/solicitacao/'),
    ('Rolândia - PR','www.rolandia.pr.gov.br','esic.rolandia.pr.gov.br/index/'),
    ('São José dos Pinhais - PR','www.sjp.pr.gov.br','servicos.sjp.pr.gov.br/servicos/esic/controller/cadastro/cad_solicitacao.php'),
    ('Sarandi - PR','www.sarandi.pr.gov.br/web','200.233.108.153:8089/portaltransparencia/esic'),
    ('Telêmaco Borba - PR','www.telemacoborba.pr.gov.br','telemacoborba.ouvidoriapublica.com.br/portal/cadastrar/informacao'),
    ('Toledo - PR','www.toledo.pr.gov.br','www.toledo.pr.gov.br/pagina/solicitacao-de-acesso-a-informacao'),
    ('Umuarama - PR','www.umuarama.pr.gov.br','servicos.umuarama.pr.gov.br/portaltransparencia/esic'),
    ('União da Vitória - PR','uniaodavitoria.pr.gov.br','e-gov.betha.com.br/transparencia/01037-091/con_registropedidoinformacao.faces'),
    ('Araranguá - SC','www.ararangua.sc.gov.br','lai.fecam.org.br/ararangua/index/solicitar-informacoes'),
    ('Balneário Camboriú - SC','www.bc.sc.gov.br','lai.fecam.org.br/balneariocamboriu/index/solicitar-informacoes'),
    ('Biguaçu - SC','bigua.atende.net','bigua.1doc.com.br/b.php?pg=wp/wp&s=bigua&itd=10&is=254'),
    ('Blumenau - SC','www.blumenau.sc.gov.br','www.blumenau.sc.gov.br/esic/esic.autenticacao.aspx'),
    ('Brusque - SC','portal.brusque.sc.gov.br','brusque.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Caçador - SC','www.cacador.sc.gov.br','cacador.1doc.com.br/b.php?pg=wp/wp&s=cacador&itd=7&is=818'),
    ('Camboriú - SC','camboriu.sc.gov.br','lai.fecam.org.br/camboriu/index/solicitar-informacoes'),
    ('Canoinhas - SC','www.pmc.sc.gov.br','lai.fecam.org.br/canoinhas/index/solicitar-informacoes'),
    ('Chapecó - SC','www.chapeco.sc.gov.br','chapeco.1doc.com.br/b.php?pg=wp/wp&s=chapeco&itd=7&is=824'),
    ('Concórdia - SC','concordia.atende.net/#!/tipo','concordia.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Criciúma - SC','www.criciuma.sc.gov.br/site','transparencia.criciuma.sc.gov.br/#iframe'),
    ('Florianópolis - SC','www.pmf.sc.gov.br','sistema.ouvidorias.gov.br/publico/SC/florianopolis/manifestacao/registrarmanifestacao'),
    ('Gaspar - SC','www.gaspar.sc.gov.br','lai.fecam.org.br/gaspar/index/solicitar-informacoes'),
    ('Içara - SC','www.icara.sc.gov.br','e-gov.betha.com.br/transparencia/01037-092/con_registropedidoinformacao.faces?mun=AShOpAHur1c='),
    ('Indaial - SC','indaial.atende.net','indaial.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Itajaí - SC','itajai.sc.gov.br','portaldocidadao.itajai.sc.gov.br/servico_link/9'),
    ('Itapema - SC','www.itapema.sc.gov.br','itapema.1doc.com.br/b.php?s=itapema&pg=o/wp&erro=t'),
    ('Jaraguá do Sul - SC','www.jaraguadosul.sc.gov.br','www.jaraguadosul.sc.gov.br/usuario/novoatendimento.php'),
    ('Joinville - SC','www.joinville.sc.gov.br','ouvidoria-form.joinville.sc.gov.br/'),
    ('Lages - SC','www.lages.sc.gov.br','e-gov.betha.com.br/transparencia/01037-091/con_registropedidoinformacao.faces'),
    ('Mafra - SC','www.mafra.sc.gov.br','lai.fecam.org.br/mafra/index/solicitar-informacoes'),
    ('Navegantes - SC','www.navegantes.sc.gov.br','sistema.ouvidorias.gov.br/publico/sc/Navegantes/Manifestacao/RegistrarManifestacao'),
    ('Palhoça - SC','palhoca.atende.net/#!/tipo','palhoca.1doc.com.br/b.php?pg=wp/wp&s=palhoca&itd=7&is=155'),
    ('Rio do Sul - SC','riodosul.atende.net','riodosul.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('São Bento do Sul - SC','www.saobeodosul.sc.gov.br','saobentodosul.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('São Francisco do Sul - SC','www.saofranciscodosul.sc.gov.br','saofranciscodosul.atende.net/?#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('São José - SC','www.saojose.sc.gov.br','ouvidoriapublica.pmsj.sc.gov.br:90/PronimOp'),
    ('Tubarão - SC','www.tubarao.sc.gov.br','tubarao.1doc.com.br/b.php?pg=wp/wp&s=tubarao&itd=15&is=246'),
    ('Videira - SC','www.videira.sc.gov.br','186.225.11.114:53251/ouvidoria/login.jsp'),
    ('Alegrete - RS','alegrete.rs.gov.br','sic.alegrete.rs.gov.br/ouvidoria/'),
    ('Alvorada - RS','www.alvorada.rs.gov.br','alvorada.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Bagé - RS','www.bage.rs.gov.br','sistema.ouvidorias.gov.br/publico/RS/Bag%C3%A9/Manifestacao/RegistrarManifestacao'),
    ('Bento Gonçalves - RS','www.bentogoncalves.rs.gov.br','bentogoncalves.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Cachoeira do Sul - RS','www.cachoeiradosul.rs.gov.br','www.cachoeiradosul.rs.gov.br/portal/sic'),
    ('Cachoeirinha - RS','cachoeirinha.atende.net/portal','cachoeirinha.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Camaquã - RS','www.camaqua.rs.gov.br','www.camaqua.rs.gov.br/portal/sic'),
    ('Campo Bom - RS','www.campobom.rs.gov.br','e-gov.betha.com.br/transparencia/01037-091/con_registropedidoinformacao.faces'),
    ('Canoas - RS','www.canoas.rs.gov.br','sistemas.canoas.rs.gov.br/transparencia/servlet/wmpedido'),
    ('Carazinho - RS','www.carazinho.rs.gov.br','www.carazinho.rs.gov.br/portal/sic'),
    ('Caxias do Sul - RS','caxias.rs.gov.br','sac.caxias.rs.gov.br/'),
    ('Cruz Alta - RS','cruzalta.atende.net/#!/tipo','cruzalta.atende.net/#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Erechim - RS','www.pmerechim.rs.gov.br','www.erechim.rs.gov.br:81/sys523/publico/sic.xhtml,jsessionid=88c79671ef8788448175868fa548?superior=3F93DBFE'),
    ('Esteio - RS','www.esteio.rs.gov.br','www.esteio.rs.gov.br/index.php?option=com_content&view=article&id=5081'),
    ('Farroupilha - RS','farroupilha.rs.gov.br','transparencia.farroupilha.rs.gov.br/?secao=acesso_informacao'),
    ('Gravataí - RS','gravatai.atende.net/#!/tipo','gravatai.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Guaíba - RS','www.guaiba.rs.gov.br','guaiba.atende.net/?pg=autoatendimento#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Ijuí - RS','www.ijui.rs.gov.br','ijui-portais.govcloud.com.br/opnet'),
    ('Lajeado - RS','www.lajeado.rs.gov.br','www.lajeado.rs.gov.br/?titulo=Portal%20da%20Transpar%EAncia&template=servico&categoria=972&codigoCategoria=972&servico=68000&idConteudo=3730'),
    ('Montenegro - RS','www.montenegro.rs.gov.br','www.montenegro.rs.gov.br/?titulo=SIC%20-%20Abertura&template=servico&categoria=1229&codigoCategoria=1229&servico=68000&idConteudo=3821'),
    ('Novo Hamburgo - RS','www.novohamburgo.rs.gov.br','transparencia.novohamburgo.rs.gov.br/modules/inscrit_quest/formulario.php?codigo=1'),
    ('Parobé - RS','parobe.atende.net','parobe.atende.net/#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Passo Fundo - RS','www.pmpf.rs.gov.br','grp.pmpf.rs.gov.br/grp/acessoexterno/programaAcessoExternoPortal.faces'),
    ('Pelotas - RS','www.pelotas.rs.gov.br','site.pelotas.com.br/transparencia/lai/'),
    ('Porto Alegre - RS','prefeitura.poa.br','sicpoa.procempa.com.br/sicpoaweb/?redirect_frag&error=invalid_request&error_description=Missing+parameter%3A+response_type#/'),
    ('Rio Grande - RS','www.riogrande.rs.gov.br','riogrande.ccanet.com.br/transparencia/pedidoacessoinformacao/solicitacaoinformacao?entidade='),
    ('Santa Cruz do Sul - RS','www.santacruz.rs.gov.br','grp.santacruz.rs.gov.br/grp/processos/acessoexterno/ouvidoria.faces'),
    ('Santa Maria - RS','www.santamaria.rs.gov.br','www.santamaria.rs.gov.br/?secao=sic&acao=pedido'),
    ('Santa Rosa - RS','www.santarosa.rs.gov.br','santarosa.atende.net/#!/tipo/servico/valor/81/padrao/1/load/1'),
    ('Santiago - RS','www.santiago.rs.gov.br','sistema.ouvidorias.gov.br/publico/Manifestacao/SelecionarTipoManifestacao.aspx'),
    ('Santo Ângelo - RS','www.santoangelo.rs.gov.br','pmsantoangelo.abase.com.br/site/sic'),
    ('São Borja - RS','www.saoborja.rs.gov.br','e-gov.betha.com.br/transparencia/01037-092/con_registropedidoinformacao.faces?mun=o5Qo4_1z4wgpFg3oR7JlwUgmmp4fK93_'),
    ('São Gabriel - RS','www.saogabriel.rs.gov.br/Portal','177.72.80.6:8081/e-sac/index/'),
    ('São Leopoldo - RS','www.saoleopoldo.rs.gov.br','www.saoleopoldo.rs.gov.br/?titulo=Servi%E7os&template=servico&categoria=407&codigoCategoria=407&servico=68000&idConteudo=2066'),
    ('Sapiranga - RS','www.sapiranga.rs.gov.br','www.sapiranga.rs.gov.br/esic/index'),
    ('Sapucaia do Sul - RS','www.sapucaiadosul.rs.gov.br','portal.sapucaiadosul.rs.gov.br/multi24/sistemas/transparencia/index?secao=faleconosco'),
    ('Taquara - RS','www.taquara.rs.gov.br','www.taquara.rs.gov.br/?titulo=Portal%20da%20Transpar%EAncia&template=servico&categoria=887&codigoCategoria=887&servico=68000&idConteudo=3392'),
    ('Uruguaiana - RS','www.uruguaiana.rs.gov.br','www.uruguaiana.rs.gov.br/esic'),
    ('Vacaria - RS','www.vacaria.rs.gov.br','esic.bst.net.br/pmVacaria.php/login/index'),
    ('Venâncio Aires - RS','www.venancioaires.rs.gov.br','grp.venancioaires.rs.gov.br/grp/processos/acessoexterno/ouvidoriaComLogradouro.faces'),
    ('Viamão - RS','www.viamao.rs.gov.br','www.viamao.rs.gov.br/portal/sic'),
    ('Campo Grande - MS','www.campogrande.ms.gov.br','sic.campogrande.ms.gov.br/cadastro'),
    ('Corumbá - MS','www.corumba.ms.gov.br','swb.corumba.ms.gov.br:8079/transparencia/SolicitarInfo.aspx'),
    ('Dourados - MS','www.dourados.ms.gov.br','esic.dourados.ms.gov.br/index.php?class=LoginForm'),
    ('Naviraí - MS','www.navirai.ms.gov.br','esic.navirai.ms.gov.br/login/'),
    ('Nova Andradina - MS','www.pmna.ms.gov.br','sic.pmna.ms.gov.br/sistema/site/index.html'),
    ('Sidrolândia - MS','www.sidrolandia.ms.gov.br','187.6.86.78:5656/transparencia/HomeESIC.aspx'),
    ('Três Lagoas - MS','www.treslagoas.ms.gov.br','xsic.com.br/treslagoas/cadastro.php'),
    ('Alta Floresta - MT','www.altafloresta.mt.gov.br','www.gp.srv.br/adm_altafloresta/ouvidoria/#/manifestacao'),
    ('Barra do Garças - MT','www.barradogarcas.mt.gov.br','fiorilli.barradogarcas.mt.gov.br:8079/transparencia/#'),
    ('Cáceres - MT','www.caceres.mt.gov.br','caceres.1doc.com.br/b.php?pg=wp/wp&s=caceres&itd=7&is=824'),
    ('Cuiabá - MT','www.cuiaba.mt.gov.br','sic.tce.mt.gov.br/47/solicitacao/index'),
    ('Lucas do Rio Verde - MT','www.lucasdorioverde.mt.gov.br/site','servico6.lucasdorioverde.mt.gov.br:8058/OuvidoriaNet/publico.aspx'),
    ('Primavera do Leste - MT','primaveradoleste.mt.gov.br','sic.tce.mt.gov.br/65/solicitacao/index'),
    ('Rondonópolis - MT','www.rondonopolis.mt.gov.br','www.rondonopolis.mt.gov.br/ouvidoria/falecidadao/index.php'),
    ('Sinop - MT','www.sinop.mt.gov.br','sic.tce.mt.gov.br/41/solicitacao/index'),
    ('Sorriso - MT','site.sorriso.mt.gov.br','site.sorriso.mt.gov.br/esic/novo'),
    ('Tangará da Serra - MT','tangaradaserra.mt.gov.br','sic.tce.mt.gov.br/40/solicitacao/index'),
    ('Várzea Grande - MT','www.varzeagrande.mt.gov.br','esic.varzeagrande.mt.gov.br/index/'),
    ('Águas Lindas de Goiás - GO','aguaslindasdegoias.go.gov.br','aguaslindasdegoias.go.gov.br/acesso-a-informacao/'),
    ('Anápolis - GO','www.anapolis.go.gov.br/portal','www.transparencia.anapolis.go.gov.br:8091/transparencia/formsic.jsf'),
    ('Aparecida de Goiânia - GO','www.aparecida.go.gov.br','transparencia.aparecida.go.gov.br/portaltransparencia/p/acessoainformacao/'),
    ('Caldas Novas - GO','www.caldasnovas.go.gov.br','portal.caldasnovas.go.gov.br:8080/sig/app.html#/transparencia/e-sic/'),
    ('Catalão - GO','www.catalao.go.gov.br/site','www.catalao.go.gov.br/esic/index/'),
    ('Cidade Ocidental - GO','www.cidadeocidental.go.gov.br','acessoainformacao.cidadeocidental.go.gov.br/informacao/sic?_ga=2.67228306.229329650.1592223596-1569733089.1592223596'),
    ('Cristalina - GO','cristalina.go.gov.br/cristalina-a-cidade-dos-cristais','prefeituradecristalina.sigepnet.com.br/informacao/sic.php?portal=2'),
    ('Formosa - GO','www.formosa.go.gov.br','acessoainformacao.formosa.go.gov.br/informacao/sic?_ga=2.12745335.1939902441.1592246890-2100764862.1592246890'),
    ('Goianésia - GO','www.goianesia.go.gov.br','aplicacoes.goianesia.go.gov.br:8080/sig/app.html#/transparencia/e-sic/'),
    ('Goiânia - GO','www.goiania.go.gov.br','www.goiania.go.gov.br/sing_transparencia/solicitar-informacao-e-sic-2-2/?filtro_plificado=mais_acessados'),
    ('Inhumas - GO','inhumas.go.gov.br','prefeituradeinhumas.sigepnet.com.br/informacao/sic.php?portal=2'),
    ('Jataí - GO','www.jatai.go.gov.br','prefeituradejatai.sigepnet.com.br/informacao/sic.php?portal=2'),
    ('Luziânia - GO','luziania.go.gov.br','gestaoluziania.com.br/sig/app.html#/transparencia/e-sic/'),
    ('Mineiros - GO','www.mineiros.go.gov.br','www.mineiros.go.gov.br/sic_bem_vindo.php'),
    ('Novo Gama - GO','novogama.go.gov.br','acessoainformacao.novogama.go.gov.br/informacao/sic?_ga=2.236994568.946003155.1592239080-44847141.1592239080'),
    ('Planaltina - GO','www.planaltina.go.gov.br','www.planaltina.go.gov.br/acessoinformacao/esic'),
    ('Rio Verde - GO','www.rioverde.go.gov.br','acessoainformacao.rioverde.go.gov.br/cidadao/ouvidoria/sic'),
    ('Senador Canedo - GO','www.senadorcanedo.go.gov.br','gestaopublica.canedo.bsit-br.com.br/portal/user-esic-register.jsf?e='),
    ('Trindade - GO','trindade.go.gov.br','acessoainformacao.trindade.go.gov.br/informacao/sic'),
    ('Valparaíso de Goiás - GO','www.valparaisodegoias.go.gov.br','acessoainformacao.valparaisodegoias.go.gov.br/informacao/sic?_ga=2.13695415.1837725312.1592243223-1683117636.1592243223'),
    ('Brasília - DF','www.df.gov.br','www.e-sic.df.gov.br/Sistema/');
