version: '3.9'
services:
  database:
    image: mysql
    volumes:
      - ${PWD}/data/:/var/lib/mysql/
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  eseek-api:
    image: node:14
    user: node
    stdin_open: true
    tty: true
    working_dir: /opt/app
    entrypoint: '/bin/bash'
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ${PWD}:/opt/app
    environment:
      - NODE_ENV=development
    depends_on:
      - database
